# 101 NumPy Exercises for Data Analysis (Python)

In [ ]:

"""
Core syntax 

np.array()
np.arange()
reshape()

np.mean()
np.median()
np.std()
np.percentile()
np.corrcoef()

np.argsort() 
np.argmax()
np.argmin()

Core Grammar of NumPy

arr[mask]                                   # filter values/rows
arr[indexes]                                # select/reorder values/rows using integer indexes
arr[:, column]                              # select a column
arr[rows, columns]                          # 2D indexing
arr[:, [1, 0, 2]]                           # select columns in a different order
arr[:, 0]                                   # select a column
arr[:4]                                     # select first rows
arr[::-1]                                   # reverse along first axis
np.isnan(arr).any()                         # check missing values
np.isnan(arr).any(axis=1)                   # check missing rows
np.where(condition, x, y)                   # select True/False values based on condition
np.unique(array, return_counts=True)        # count categories
(arr - arr.min()) / (arr.max() - arr.min()) # min-max normalization
np.corrcoef(x, y)[0, 1]                     # pearson correlation coefficient
np.percentile(array, q=[])                  # calculate percentiles
arr[arr.argsort()]                          # sort a 1D array using argsort indexes
np.argsort(-a)                              # sort a 1D array in descending order using argsort indexes
np.clip(array, min_value, max_value)        # clip array values to a range
np.random.uniform(low, high, size)          # generate random numbers from uniform distribution
np.argpartition(array, k)                   # partition array to get k smallest values (unsorted)
"""

## 1. Import NumPy and Check the Version

Import numpy as np and print the version number.

Difficulty Level: L1

Desired Output:

1.13.3

Why this matters: Verifying the NumPy version ensures compatibility with your code and helps debug version-specific behavior differences.

In [2]:
import numpy as np

print(np.__version__)

2.4.6


## 2. Create a 1D Array

Create a 1D array of numbers from 0 to 9.

Difficulty Level: L1

Desired Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Why this matters: Creating sequential arrays is the starting point for indexing exercises, test data generation, and understanding how NumPy stores data in memory.


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Create a Boolean Array

Create a 3×3 numpy array of all True values.

Difficulty Level: L1

Desired Output:

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
 
Why this matters: Boolean arrays are used as masks for filtering data, and understanding how to create them is essential for conditional selection in data analysis.

In [ ]:
# full() is used to create an array filled with a specified value.
arr1 = np.full((3,3,), True)

# or

# ones() is used to create an array filled with ones, and by specifying dtype=bool, 1 = True.
arr2 = np.ones((3, 3), dtype=bool)

print(arr1)
print(arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## 4. Extract Items That Satisfy a Condition

Extract all odd numbers from arr.

Difficulty Level: L1

Desired Output:

array([1, 3, 5, 7, 9])

Why this matters: Boolean indexing is the primary way to filter rows in data cleaning and subsetting datasets before analysis.

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

mask = arr % 2 != 0

# or

result = arr[arr % 2 == 1]

print(arr[mask])
print(result)

[1 3 5 7 9]
[1 3 5 7 9]


## 5. Replace Items That Satisfy a Condition

Replace all odd numbers in arr with -1.

Difficulty Level: L1

Desired Output:

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Why this matters: Conditional replacement is used to handle outliers, recode categories, and clean invalid entries in datasets.

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

mask = arr % 2 != 0

arr[mask]        # read/select values
arr[mask] = -1   # write/replace selected values

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 6. Replace Items Without Affecting the Original Array

Replace all odd numbers in arr with -1 without modifying the original arr.

Difficulty Level: L2

Desired Output:

out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
arr: [0 1 2 3 4 5 6 7 8 9]

Why this matters: Preserving the original data while creating transformed copies is critical in ML pipelines where you need both raw and processed versions of features.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

new = arr.copy()

mask = new % 2 != 0

new[mask] = -1

print(new)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# np.where(condition, value_if_true, value_if_false)
out = np.where(arr % 2 == 1, -1, arr)
print("out:", out)
print("arr:", arr)

out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
arr: [0 1 2 3 4 5 6 7 8 9]


## 7. Reshape an Array

Convert the 1D array arr to a 2D array with 2 rows.

Difficulty Level: L1

Desired Output:

[[0 1 2 3 4]
 [5 6 7 8 9]]
 
Why this matters: Reshaping is one of the most common operations when preparing data for ML models, which expect inputs in specific shapes (e.g., batches of samples).

In [ ]:
arr = np.arange(10)

arr.reshape(2,5)

# or

arr.reshape(2, -1) # -1 means "unspecified", will figure correct size

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. Stack Two Arrays Vertically

Stack arrays a and b vertically.

Difficulty Level: L2

Desired Output:

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
 
Why this matters: Vertical stacking is used to combine datasets, append new observations to existing data, or merge training and validation sets.

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# axis=0 means concatenate along rows (vertical stack)
# axis=1 means concatenate along columns (horizontal stack)
# same as vstack() and hstack() respectively
result = np.concatenate([a, b], axis=0)
print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 9. Stack Two Arrays Horizontally

Stack arrays a and b horizontally.

Difficulty Level: L2

Desired Output:

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
 
Why this matters: Horizontal stacking is used to add new features (columns) to a dataset, such as appending engineered features alongside existing ones.

In [31]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

result = np.concatenate([a, b], axis=1)

print(result)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## 10. Generate Custom Sequences Without Hardcoding

Using only numpy functions and the input array a, produce an array that first repeats each element 3 times, then tiles the whole array 3 times.

Difficulty Level: L2

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Why this matters: Programmatic sequence generation is essential for creating repeated patterns in simulations, data augmentation, and feature engineering.

In [ ]:
a = np.array([1,2,3])

# repeat() repeats each element of the array a specified number of times.
# tile() repeats the whole array a specified number of times.
result = np.concatenate([np.repeat(a, 3), np.tile(a, 3)])
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## 11. Get Common Items Between Two Arrays

Find the common items between arrays a and b.

Difficulty Level: L2

Desired Output:

[2 4]

Why this matters: Set intersection is used in data cleaning to find shared records, overlapping features, or matching IDs across datasets.

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# intersect1d() finds the common elements between two arrays and returns them in sorted order.
result = np.intersect1d(a, b)
print(result)

[2 4]


## 12. Remove Items Present in Another Array

From array a, remove all items that are present in array b.

Difficulty Level: L2

Desired Output:

[1 2 3 4]

Why this matters: Set difference operations are used to exclude known values, filter out stop words, or remove already-processed records from a pipeline.

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# setdiff1d() finds the elements that are in the first array but not in the second array.
result = np.setdiff1d(a, b)  

print(result)

[1 2 3 4]


## 13. Find Positions Where Two Arrays Match

Get the positions (indices) where elements of a and b are equal.

Difficulty Level: L2

Desired Output:

(array([1, 3, 5, 7]),)

Why this matters: Finding matching positions is used in evaluation metrics (e.g., comparing predicted vs. actual labels) and aligning paired datasets.

In [40]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# where() returns the indices where condition you have input is True.
# can access index array using result[0] and result[1] for row and column indices respectively.
result = np.where(a == b)
print(result)

(array([1, 3, 5, 7]),)


## 14. Extract Numbers Within a Given Range

From array a, extract all items between 5 and 10 (inclusive).

Difficulty Level: L2

Desired Output:

[ 6  9 10]

Why this matters: Range-based filtering is used for outlier removal, selecting data within valid bounds, and binning continuous variables.

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
result = a[(a >= 5) & (a <= 10)] # & is used for element-wise logical AND operation
print(result)

# Method 2:
# index = np.where((a >= 5) & (a <= 10))
# print(a[index])

# Method 3:
# index = np.where(np.logical_and(a>=5, a<=10))
# print(a[index])

[ 6  9 10]


## 16. Swap Two Columns in a 2D Array

Swap columns 1 and 2 in the array arr.

Difficulty Level: L2

Desired Output:

[[1 0 2]
 [4 3 5]
 [7 6 8]]
 
Why this matters: Reordering columns is a common step when aligning feature order across datasets or when a model expects features in a specific sequence.

In [ ]:
arr = np.arange(9).reshape(3,3)

# : is used to select all elements along a particular axis.
# syntax is [rows, columns]
arr = arr[:, [1,0,2]]

print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


## 17. Swap Two Rows in a 2D Array

Swap rows 1 and 2 in the array arr.

Difficulty Level: L2

Desired Output:

[[3 4 5]
 [0 1 2]
 [6 7 8]]
 
Why this matters: Row swapping is used in data shuffling, reordering observations, and implementing custom sorting logic for training data.


In [ ]:
arr = np.arange(9).reshape(3,3)

# change order of rows 
result = arr[[1,0,2], :]
print(result)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


## 18. Reverse the Rows of a 2D Array

Reverse the row order of the 2D array arr.

Difficulty Level: L2

Desired Output:

[[6 7 8]
 [3 4 5]
 [0 1 2]]
 
Why this matters: Reversing rows is used in image flipping for data augmentation and in time series analysis to process data from most recent to oldest.


In [ ]:
arr = np.arange(9).reshape(3,3)

result = arr[[2,1,0], :]

# or 

result = arr[::-1] # start:stop:step, step=-1 means reverse the order. reverse order of rows, keep columns unchanged.

print(result)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


## 19. Reverse the Columns of a 2D Array

Reverse the column order of the 2D array arr.

Difficulty Level: L2

Desired Output:

[[2 1 0]
 [5 4 3]
 [8 7 6]]
 
Why this matters: Column reversal is used in image mirroring for data augmentation and when reordering features for visualization.

In [ ]:
arr = np.arange(9).reshape(3,3)

result = arr[:, ::-1] # : means select all rows, ::-1 means reverse the order of columns
print(result)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## 20. Create a 2D Array of Random Floats Between 5 and 10

Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.

Difficulty Level: L2

Desired Output:

[[ 8.501  9.105  6.859]
 [ 9.763  9.877  7.135]
 [ 7.49   8.334  6.168]
 [ 7.75   9.945  5.274]
 [ 8.085  5.562  7.312]]
 
Why this matters: Generating random arrays within a specific range is used in weight initialization for neural networks and in Monte Carlo simulations.

In [ ]:
# Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
# print(rand_arr)

# Method 2:
rand_arr = np.random.uniform(5, 10, size=(5,3)) # np.random.uniform(low, high, size=shape), uniform distribution between low and high
print(rand_arr)

[[6.89999615 6.05560015 6.4913157 ]
 [7.22950249 8.74042794 8.72744079]
 [7.42032186 5.11116854 9.97906789]
 [7.55427384 7.61384186 6.51011206]
 [5.98524229 5.61093196 7.41212958]]


## 28. Compute Mean, Median, and Standard Deviation

Find the mean, median, and standard deviation of the sepallength column (1st column) from the iris dataset.

Difficulty Level: L1

Desired Output:

5.84333333333 5.8 0.825301291785

Why this matters: These three summary statistics are the foundation of exploratory data analysis and are used to understand data distribution before building any model.

In [55]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# genfromtxt() is used to load data from a text file
# np.genfromtxt(source, delimiter=",", dtype=..., usecols=...) is the pattern
sepallength = np.genfromtxt(
    url,
    delimiter=",",
    dtype=float,
    usecols=0
)

mean = np.mean(sepallength)
median = np.median(sepallength)
std = np.std(sepallength)

print(mean, median, std)

5.843333333333334 5.8 0.8253012917851409


## 29. Normalize an Array to the 0-1 Range

Normalize the sepallength array so the minimum maps to 0 and the maximum maps to 1.

Difficulty Level: L2

Desired Output:

[ 0.222  0.167  0.111  0.083  0.194  0.306  0.083  0.194  0.028  0.167
  0.306  0.139  0.139  0.     0.417  0.389  0.306  0.222  0.389  0.222
  0.306  0.222  0.083  0.222  0.139  0.194  0.194  0.25   0.25   0.111
  0.139  0.306  0.25   0.333  0.167  0.194  0.333  0.167  0.028  0.222
  0.194  0.056  0.028  0.194  0.222  0.139  0.222  0.083  0.278  0.194
  0.75   0.583  0.722  0.333  0.611  0.389  0.556  0.167  0.639  0.25
  0.194  0.444  0.472  0.5    0.361  0.667  0.361  0.417  0.528  0.361
  0.444  0.5    0.556  0.5    0.583  0.639  0.694  0.667  0.472  0.389
  0.333  0.333  0.417  0.472  0.306  0.472  0.667  0.556  0.361  0.333
  0.333  0.5    0.417  0.194  0.361  0.389  0.389  0.528  0.222  0.389
  0.556  0.417  0.778  0.556  0.611  0.917  0.167  0.833  0.667  0.806
  0.611  0.583  0.694  0.389  0.417  0.583  0.611  0.944  0.944  0.472
  0.722  0.361  0.944  0.556  0.667  0.806  0.528  0.5    0.583  0.806
  0.861  1.     0.583  0.556  0.5    0.944  0.556  0.583  0.472  0.722
  0.667  0.722  0.417  0.694  0.667  0.667  0.556  0.611  0.528  0.444]
  
Why this matters: Min-max normalization is a standard preprocessing step for ML algorithms (e.g., KNN, SVM) that are sensitive to feature scales.


In [57]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Find the maximum and minimum values of the array
minimum = sepallength.min()
maximum = sepallength.max()

# Normalize the array to the range [0, 1] using the formula: (x - min) / (max - min)
# max - min gives the range for the data
# subtract every value in the array by the min value, then divide by the range to scale the values to [0, 1]
normalised = (sepallength - minimum) / (maximum - minimum)

print(np.round(normalised, 3))

[0.222 0.167 0.111 0.083 0.194 0.306 0.083 0.194 0.028 0.167 0.306 0.139
 0.139 0.    0.417 0.389 0.306 0.222 0.389 0.222 0.306 0.222 0.083 0.222
 0.139 0.194 0.194 0.25  0.25  0.111 0.139 0.306 0.25  0.333 0.167 0.194
 0.333 0.167 0.028 0.222 0.194 0.056 0.028 0.194 0.222 0.139 0.222 0.083
 0.278 0.194 0.75  0.583 0.722 0.333 0.611 0.389 0.556 0.167 0.639 0.25
 0.194 0.444 0.472 0.5   0.361 0.667 0.361 0.417 0.528 0.361 0.444 0.5
 0.556 0.5   0.583 0.639 0.694 0.667 0.472 0.389 0.333 0.333 0.417 0.472
 0.306 0.472 0.667 0.556 0.361 0.333 0.333 0.5   0.417 0.194 0.361 0.389
 0.389 0.528 0.222 0.389 0.556 0.417 0.778 0.556 0.611 0.917 0.167 0.833
 0.667 0.806 0.611 0.583 0.694 0.389 0.417 0.583 0.611 0.944 0.944 0.472
 0.722 0.361 0.944 0.556 0.667 0.806 0.528 0.5   0.583 0.806 0.861 1.
 0.583 0.556 0.5   0.944 0.556 0.583 0.472 0.722 0.667 0.722 0.417 0.694
 0.667 0.667 0.556 0.611 0.528 0.444]


## 30. Compute the Softmax Score

Compute the softmax scores for the sepallength array.

Difficulty Level: L3

Desired Output:

[ 0.002  0.002  0.001  0.001  0.002  0.003  0.001  0.002  0.001  0.002
  0.003  0.002  0.002  0.001  0.004  0.004  0.003  0.002  0.004  0.002
  0.003  0.002  0.001  0.002  0.002  0.002  0.002  0.002  0.002  0.001
  0.002  0.003  0.002  0.003  0.002  0.002  0.003  0.002  0.001  0.002
  0.002  0.001  0.001  0.002  0.002  0.002  0.002  0.001  0.003  0.002
  0.015  0.008  0.013  0.003  0.009  0.004  0.007  0.002  0.01   0.002
  0.002  0.005  0.005  0.006  0.004  0.011  0.004  0.004  0.007  0.004
  0.005  0.006  0.007  0.006  0.008  0.01   0.012  0.011  0.005  0.004
  0.003  0.003  0.004  0.005  0.003  0.005  0.011  0.007  0.004  0.003
  0.003  0.006  0.004  0.002  0.004  0.004  0.004  0.007  0.002  0.004
  0.007  0.004  0.016  0.007  0.009  0.027  0.002  0.02   0.011  0.018
  0.009  0.008  0.012  0.004  0.004  0.008  0.009  0.03   0.03   0.005
  0.013  0.004  0.03   0.007  0.011  0.018  0.007  0.006  0.008  0.018
  0.022  0.037  0.008  0.007  0.006  0.03   0.007  0.008  0.005  0.013
  0.011  0.013  0.004  0.012  0.011  0.011  0.007  0.009  0.007  0.005]

Why this matters: Softmax converts raw scores into probabilities and is the final activation function in most classification neural networks.

In [60]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

def softmax(x):
    """
    Compute softmax values for each sets of scores in x.

    Softmax is a function that takes as input a vector of real numbers and normalizes it into a probability distribution. 
    The output values are in the range (0, 1) and sum to 1. 

    The softmax function is often used in machine learning, particularly in classification problems, to convert raw scores (logits) into probabilities.
    """
    e_x = np.exp(x - np.max(x)) # subtracting np.max(x) for numerical stability
    return e_x / e_x.sum(axis=0) # divide the exponentials by the sum of exponentials to get probabilities

print(softmax(sepallength))

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

## 31. Find Percentile Scores

Find the 5th and 95th percentile of the sepallength array.

Difficulty Level: L1

Desired Output:

[ 4.6    7.255]

Why this matters: Percentiles are used to detect outliers, set clipping thresholds, and define confidence intervals in statistical analysis.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# pattern is np.percentile(array, q=[lower_percentile, upper_percentile]). where q = quantile.
result = np.percentile(sepallength, q=[5, 95])
print(result)

[4.6   7.255]


## 34. Filter a NumPy Array Based on Multiple Conditions

Filter the rows of iris_2d where petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0.

Difficulty Level: L3

Desired Output:

[[ 4.8  3.4  1.6  0.2]
 [ 4.8  3.4  1.9  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 4.9  2.4  3.3  1. ]
 [ 4.9  2.5  4.5  1.7]]
 
Why this matters: Multi-condition filtering is used constantly in data analysis to subset records that meet specific criteria, such as selecting high-risk patients or underperforming products.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# using boolean indexing to filter rows based on multiple conditions
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
# filter the rows of iris_2d based on the condition
result = iris_2d[condition]
print(result)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## 35. Drop Rows Containing Missing Values

Select the rows of iris_2d that do not have any nan value, keeping only complete rows.

Difficulty Level: L3

Desired Output:

array([[ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4]])
       
Why this matters: Dropping rows with missing values is a standard data cleaning step before training ML models that cannot handle NaN inputs.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Introduce some nan values for the exercise
# 20 random integers fro 0 to 149 inclusive (Pick 20 random row positions from the 150 rows).
# indexing pattern iris_2d[row_indexes, column_indexes] selects specific cells
# NumPy creates 20 random row indexes and 20 random column indexes, pairs them together, and replaces those 20 selected cells with np.nan.
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Find missing cells
missing_cells = np.isnan(iris_2d)

# Find rows that contain at least one missing cell
rows_with_missing = missing_cells.any(axis=1)

# Invert the mask to find complete rows
complete_rows = ~rows_with_missing

# Keep only complete rows
result = iris_2d[complete_rows]

print(result)

# for missing rows rows_with_missing = np.isnan(data).any(axis=1)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [4.5 2.3 1.3 0.3]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.

## 36. Find Correlation Between Two Columns

Compute the Pearson correlation between SepalLength (1st column) and PetalLength (3rd column) in iris_2d.

Difficulty Level: L2

Desired Output:

0.871754157305

Why this matters: Correlation analysis is a core step in exploratory data analysis and feature selection for ML models.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

SLength = iris_2d[:, 0]
PLength = iris_2d[:, 2]

# Correlation coefficient is a measure of the linear relationship between two variables. It ranges from -1 to 1, where:
# - 1 indicates a perfect negative linear relationship,
# 0 indicates no linear relationship, and
# 1 indicates a perfect positive linear relationship.
# It is a standardized measure of the strength and direction of the linear relationship between two variables. 
# It is calculated as the covariance of the two variables divided by the product of their standard deviations.

# Calculate the correlation coefficient between SLength and PLength using np.corrcoef()
# returns a correlation matrix, where the element at position (0, 1) is the correlation coefficient between SLength and PLength.
matrix = np.corrcoef(SLength, PLength)

# matrix[0, 0] = correlation of SLength with SLength = 1.0
# matrix[0, 1] = correlation of SLength with PLength = r
# matrix[1, 0] = correlation of PLength with SLength = r
# matrix[1, 1] = correlation of PLength with PLength = 1.0
# [0,1] is the position of the correlation coefficient between SLength and PLength in the correlation matrix.
r = matrix[0,1]

print(r)

# Solution 1
print(np.corrcoef(iris[:, 0], iris[:, 2])[0, 1])

from scipy.stats.stats import pearsonr
# Solution 2
corr, p_value = pearsonr(iris[:, 0], iris[:, 2])
print(corr)

0.8717541573048713


## 37. Check for Missing Values in an Array

Determine whether iris_2d has any missing (nan) values and print the boolean result.

Difficulty Level: L2

Desired Output:

False

Why this matters: Detecting missing values early prevents silent errors in downstream computations like aggregation and model training.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Check for any missing values in the iris_2d array
missing_values = np.isnan(iris_2d).any()

print(missing_values)

False


## 38. Replace All Missing Values with Zero

Replace all nan values in iris_2d with 0 and print the first four rows.

Difficulty Level: L2

Desired Output:

array([[ 5.1,  3.5,  1.4,  0. ],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2]])
       
Why this matters: Imputing missing values with zero is a quick baseline strategy in data cleaning pipelines before more sophisticated imputation.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# mask for missing values in the iris_2d array
missing_values = np.isnan(iris_2d)

# Replace missing values with 0
iris_2d[missing_values] = 0

# print the first 4 rows of the modified iris_2d array
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [0.  3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


## 39. Count Unique Values in an Array

Find the unique values and their counts in the species column of the iris dataset.

Difficulty Level: L2

Desired Output:

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50]))
       
Why this matters: Checking class distribution is essential before training classifiers to detect imbalanced datasets.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Loop through every row and add the 5th column (index 4) to a list, then convert the list to a NumPy array.
species = np.array([row.tolist()[4] for row in iris])

# or 

# Extract the species column using slicing, only the 5th column (index 4) is selected from the iris array.
species = iris[:, 4]

# returns 2 arrays:
# 1. the unique values
# 2. how many times each value appears
print(np.unique(species, return_counts=True))

# or

# Using np.genfromtxt() to directly extract the species column from the iris dataset.
species = np.genfromtxt(
    url,
    delimiter=",",
    dtype=str, 
    usecols=4 # select only the 5th column (index 4) which contains the species names
)

# return both arrays
unique_species, counts = np.unique(species, return_counts=True)
print(unique_species)
print(counts)

# core pattern
# unique_values, counts = np.unique(array, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([50, 50, 50]))
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[50 50 50]


## 44. Sort a 2D Array by a Column

Sort the iris dataset based on the sepallength column (1st column) in ascending order.

Difficulty Level: L2

Desired Output:

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]
 
Why this matters: Sorting datasets by a specific feature is fundamental for ranking, binary search, and ordered visualizations.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Extract the sepal length column (first column, index 0) from the iris dataset and convert it to float type
# argsort() will sort numerically, not as text
sepal_length = iris[:, 0].astype(float)

# Sort the sepal length values and get the indexes of the sorted values using argsort()
sorted_indexes = sepal_length.argsort()

# Use the sorted indexes to sort the entire iris dataset based on ascending sepal length
# this is integer array indexing
sorted_iris = iris[sorted_indexes]

# Print the first 20 rows of the sorted iris dataset
print(sorted_iris[:20])

# or 

# compact version
print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]
[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0

## 45. Find the Most Frequent Value in an Array

Find the most frequent value of petal length (3rd column) in the iris dataset.

Difficulty Level: L1

Desired Output:

b'1.5'

Why this matters: Identifying the mode of a feature helps detect dominant patterns and is used in imputation strategies.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# extract all the rows of the 3rd column (index 2) which is petal length
column = iris[:, 2] 

# get the unique values and their counts in the petal length column
values, counts = np.unique(column, return_counts=True) 

# Find the maximum value in the petal length column based on the counts of unique values
# argmax() returns index of the single largest value
maximum = values[np.argmax(counts)]

print(maximum)

b'1.5'


## 47. Clip Array Values to a Range

From the array a, replace all values greater than 30 with 30 and all values less than 10 with 10.

Difficulty Level: L2

Desired Output:

[ 27.63  14.64  21.8   30.    10.    10.    30.    30.    10.    29.18  30.
  11.25  10.08  10.    11.77  30.    30.    10.    30.    14.43]
  
Why this matters: Clipping values to a valid range is essential for outlier handling and ensuring inputs stay within expected bounds for models.

In [ ]:
# same random numbers 
np.random.seed(100) 

# generate 20 random numbers between 1 and 50 from a uniform distribution
a = np.random.uniform(1, 50, 20)

# Solution 1: Using np.clip
print(np.clip(a, a_min=10, a_max=30)) # force all values into a fixed range between 10 and 30.

# Solution 2: Using np.where
# nested conditional
# if_true: if a < 10, return 10
# if_false: if a > 30, return 30 if_true, if_false return a
print(np.where(a < 10, 10, np.where(a > 30, 30, a))) 

# Solution 3: Using boolean indexing
result = a.copy()
result[result > 30] = 30
result[result < 10] = 10

print(result)

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


## 48. Get the Positions of Top N Values

Get the positions of the top 5 maximum values in the array a.

Difficulty Level: L2

Desired Output:

[18 7 3 10 15]

Why this matters: Finding top-N indices is used in ranking systems, recommendation engines, and selecting the highest-confidence predictions.

In [ ]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

# Solution 1:
# argsort() returns the indices that would sort an array.
index_sorted = np.argsort(a)

# Get the last 5 elements of the sorted array, which are the top 5 largest values.
top_5 = index_sorted[-5:]
print(top_5)

# Get the actual values
print(a[top_5])

# Solution 2:
# Simpler version of solution 1
print(a.argsort()[-5:])

# Solution 3:
# Does partial sorting
# argpartition() returns the indices that would partition an array into two parts: 
# the first part contains the k smallest elements, and the second part contains the rest of the elements.
# 5 means the 5 smallest values of -a are in the first 5 positions, the rest are left.
#[:5] selects the first 5 indices, they will be the 5 largest values but won't be sorted.
print(np.argpartition(-a, 5)[:5])

# Get the actual values:
print(a[a.argsort()][-5:])

[18  7  3 10 15]
[18  7  3 10 15]
[15 10  3  7 18]
[40.99501269 41.466785   42.39403048 44.67477576 48.95256545]
