# 101 NumPy Exercises for Data Analysis (Python)

## 1. Import NumPy and Check the Version

Import numpy as np and print the version number.

Difficulty Level: L1

Desired Output:

1.13.3

Why this matters: Verifying the NumPy version ensures compatibility with your code and helps debug version-specific behavior differences.

In [2]:
import numpy as np

print(np.__version__)

2.4.6


## 2. Create a 1D Array

Create a 1D array of numbers from 0 to 9.

Difficulty Level: L1

Desired Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Why this matters: Creating sequential arrays is the starting point for indexing exercises, test data generation, and understanding how NumPy stores data in memory.


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Create a Boolean Array

Create a 3×3 numpy array of all True values.

Difficulty Level: L1

Desired Output:

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
 
Why this matters: Boolean arrays are used as masks for filtering data, and understanding how to create them is essential for conditional selection in data analysis.

In [ ]:
# full() is used to create an array filled with a specified value.
arr1 = np.full((3,3,), True)

# or

# ones() is used to create an array filled with ones, and by specifying dtype=bool, 1 = True.
arr2 = np.ones((3, 3), dtype=bool)

print(arr1)
print(arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## 4. Extract Items That Satisfy a Condition

Extract all odd numbers from arr.

Difficulty Level: L1

Desired Output:

array([1, 3, 5, 7, 9])

Why this matters: Boolean indexing is the primary way to filter rows in data cleaning and subsetting datasets before analysis.

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

mask = arr % 2 != 0

# or

result = arr[arr % 2 == 1]

print(arr[mask])
print(result)

[1 3 5 7 9]
[1 3 5 7 9]


## 5. Replace Items That Satisfy a Condition

Replace all odd numbers in arr with -1.

Difficulty Level: L1

Desired Output:

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Why this matters: Conditional replacement is used to handle outliers, recode categories, and clean invalid entries in datasets.

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

mask = arr % 2 != 0

arr[mask]        # read/select values
arr[mask] = -1   # write/replace selected values

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 6. Replace Items Without Affecting the Original Array

Replace all odd numbers in arr with -1 without modifying the original arr.

Difficulty Level: L2

Desired Output:

out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
arr: [0 1 2 3 4 5 6 7 8 9]

Why this matters: Preserving the original data while creating transformed copies is critical in ML pipelines where you need both raw and processed versions of features.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

new = arr.copy()

mask = new % 2 != 0

new[mask] = -1

print(new)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# np.where(condition, value_if_true, value_if_false)
out = np.where(arr % 2 == 1, -1, arr)
print("out:", out)
print("arr:", arr)

out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
arr: [0 1 2 3 4 5 6 7 8 9]


## 7. Reshape an Array

Convert the 1D array arr to a 2D array with 2 rows.

Difficulty Level: L1

Desired Output:

[[0 1 2 3 4]
 [5 6 7 8 9]]
 
Why this matters: Reshaping is one of the most common operations when preparing data for ML models, which expect inputs in specific shapes (e.g., batches of samples).

In [ ]:
arr = np.arange(10)

arr.reshape(2,5)

# or

arr.reshape(2, -1) # -1 means "unspecified", will figure correct size

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. Stack Two Arrays Vertically

Stack arrays a and b vertically.

Difficulty Level: L2

Desired Output:

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
 
Why this matters: Vertical stacking is used to combine datasets, append new observations to existing data, or merge training and validation sets.

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# axis=0 means concatenate along rows (vertical stack)
# axis=1 means concatenate along columns (horizontal stack)
# same as vstack() and hstack() respectively
result = np.concatenate([a, b], axis=0)
print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 9. Stack Two Arrays Horizontally

Stack arrays a and b horizontally.

Difficulty Level: L2

Desired Output:

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
 
Why this matters: Horizontal stacking is used to add new features (columns) to a dataset, such as appending engineered features alongside existing ones.

In [31]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

result = np.concatenate([a, b], axis=1)

print(result)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## 10. Generate Custom Sequences Without Hardcoding

Using only numpy functions and the input array a, produce an array that first repeats each element 3 times, then tiles the whole array 3 times.

Difficulty Level: L2

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Why this matters: Programmatic sequence generation is essential for creating repeated patterns in simulations, data augmentation, and feature engineering.

In [ ]:
a = np.array([1,2,3])

# repeat() repeats each element of the array a specified number of times.
# tile() repeats the whole array a specified number of times.
result = np.concatenate([np.repeat(a, 3), np.tile(a, 3)])
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## 11. Get Common Items Between Two Arrays

Find the common items between arrays a and b.

Difficulty Level: L2

Desired Output:

[2 4]

Why this matters: Set intersection is used in data cleaning to find shared records, overlapping features, or matching IDs across datasets.

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# intersect1d() finds the common elements between two arrays and returns them in sorted order.
result = np.intersect1d(a, b)
print(result)

[2 4]


## 12. Remove Items Present in Another Array

From array a, remove all items that are present in array b.

Difficulty Level: L2

Desired Output:

[1 2 3 4]

Why this matters: Set difference operations are used to exclude known values, filter out stop words, or remove already-processed records from a pipeline.

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# setdiff1d() finds the elements that are in the first array but not in the second array.
result = np.setdiff1d(a, b)  

print(result)

[1 2 3 4]


## 13. Find Positions Where Two Arrays Match

Get the positions (indices) where elements of a and b are equal.

Difficulty Level: L2

Desired Output:

(array([1, 3, 5, 7]),)

Why this matters: Finding matching positions is used in evaluation metrics (e.g., comparing predicted vs. actual labels) and aligning paired datasets.

In [40]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# where() returns the indices where condition you have input is True.
# can access index array using result[0] and result[1] for row and column indices respectively.
result = np.where(a == b)
print(result)

(array([1, 3, 5, 7]),)


## 14. Extract Numbers Within a Given Range

From array a, extract all items between 5 and 10 (inclusive).

Difficulty Level: L2

Desired Output:

[ 6  9 10]

Why this matters: Range-based filtering is used for outlier removal, selecting data within valid bounds, and binning continuous variables.

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
result = a[(a >= 5) & (a <= 10)] # & is used for element-wise logical AND operation
print(result)

# Method 2:
# index = np.where((a >= 5) & (a <= 10))
# print(a[index])

# Method 3:
# index = np.where(np.logical_and(a>=5, a<=10))
# print(a[index])

[ 6  9 10]


## 16. Swap Two Columns in a 2D Array

Swap columns 1 and 2 in the array arr.

Difficulty Level: L2

Desired Output:

[[1 0 2]
 [4 3 5]
 [7 6 8]]
 
Why this matters: Reordering columns is a common step when aligning feature order across datasets or when a model expects features in a specific sequence.

In [ ]:
arr = np.arange(9).reshape(3,3)

# : is used to select all elements along a particular axis.
# syntax is [rows, columns]
arr = arr[:, [1,0,2]]

print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


## 17. Swap Two Rows in a 2D Array

Swap rows 1 and 2 in the array arr.

Difficulty Level: L2

Desired Output:

[[3 4 5]
 [0 1 2]
 [6 7 8]]
 
Why this matters: Row swapping is used in data shuffling, reordering observations, and implementing custom sorting logic for training data.


In [ ]:
arr = np.arange(9).reshape(3,3)

# change order of rows 
result = arr[[1,0,2], :]
print(result)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


## 18. Reverse the Rows of a 2D Array

Reverse the row order of the 2D array arr.

Difficulty Level: L2

Desired Output:

[[6 7 8]
 [3 4 5]
 [0 1 2]]
 
Why this matters: Reversing rows is used in image flipping for data augmentation and in time series analysis to process data from most recent to oldest.


In [ ]:
arr = np.arange(9).reshape(3,3)

result = arr[[2,1,0], :]

# or 

result = arr[::-1] # start:stop:step, step=-1 means reverse the order. reverse order of rows, keep columns unchanged.

print(result)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


## 19. Reverse the Columns of a 2D Array

Reverse the column order of the 2D array arr.

Difficulty Level: L2

Desired Output:

[[2 1 0]
 [5 4 3]
 [8 7 6]]
 
Why this matters: Column reversal is used in image mirroring for data augmentation and when reordering features for visualization.

In [ ]:
arr = np.arange(9).reshape(3,3)

result = arr[:, ::-1] # : means select all rows, ::-1 means reverse the order of columns
print(result)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## 20. Create a 2D Array of Random Floats Between 5 and 10

Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.

Difficulty Level: L2

Desired Output:

[[ 8.501  9.105  6.859]
 [ 9.763  9.877  7.135]
 [ 7.49   8.334  6.168]
 [ 7.75   9.945  5.274]
 [ 8.085  5.562  7.312]]
 
Why this matters: Generating random arrays within a specific range is used in weight initialization for neural networks and in Monte Carlo simulations.

In [ ]:
# Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
# print(rand_arr)

# Method 2:
rand_arr = np.random.uniform(5, 10, size=(5,3)) # np.random.uniform(low, high, size=shape), uniform distribution between low and high
print(rand_arr)

[[6.89999615 6.05560015 6.4913157 ]
 [7.22950249 8.74042794 8.72744079]
 [7.42032186 5.11116854 9.97906789]
 [7.55427384 7.61384186 6.51011206]
 [5.98524229 5.61093196 7.41212958]]


## 28. Compute Mean, Median, and Standard Deviation

Find the mean, median, and standard deviation of the sepallength column (1st column) from the iris dataset.

Difficulty Level: L1

Desired Output:

5.84333333333 5.8 0.825301291785

Why this matters: These three summary statistics are the foundation of exploratory data analysis and are used to understand data distribution before building any model.

In [55]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# genfromtxt() is used to load data from a text file
# np.genfromtxt(source, delimiter=",", dtype=..., usecols=...) is the pattern
sepallength = np.genfromtxt(
    url,
    delimiter=",",
    dtype=float,
    usecols=0
)

mean = np.mean(sepallength)
median = np.median(sepallength)
std = np.std(sepallength)

print(mean, median, std)

5.843333333333334 5.8 0.8253012917851409


## 29. Normalize an Array to the 0-1 Range

Normalize the sepallength array so the minimum maps to 0 and the maximum maps to 1.

Difficulty Level: L2

Desired Output:

[ 0.222  0.167  0.111  0.083  0.194  0.306  0.083  0.194  0.028  0.167
  0.306  0.139  0.139  0.     0.417  0.389  0.306  0.222  0.389  0.222
  0.306  0.222  0.083  0.222  0.139  0.194  0.194  0.25   0.25   0.111
  0.139  0.306  0.25   0.333  0.167  0.194  0.333  0.167  0.028  0.222
  0.194  0.056  0.028  0.194  0.222  0.139  0.222  0.083  0.278  0.194
  0.75   0.583  0.722  0.333  0.611  0.389  0.556  0.167  0.639  0.25
  0.194  0.444  0.472  0.5    0.361  0.667  0.361  0.417  0.528  0.361
  0.444  0.5    0.556  0.5    0.583  0.639  0.694  0.667  0.472  0.389
  0.333  0.333  0.417  0.472  0.306  0.472  0.667  0.556  0.361  0.333
  0.333  0.5    0.417  0.194  0.361  0.389  0.389  0.528  0.222  0.389
  0.556  0.417  0.778  0.556  0.611  0.917  0.167  0.833  0.667  0.806
  0.611  0.583  0.694  0.389  0.417  0.583  0.611  0.944  0.944  0.472
  0.722  0.361  0.944  0.556  0.667  0.806  0.528  0.5    0.583  0.806
  0.861  1.     0.583  0.556  0.5    0.944  0.556  0.583  0.472  0.722
  0.667  0.722  0.417  0.694  0.667  0.667  0.556  0.611  0.528  0.444]
  
Why this matters: Min-max normalization is a standard preprocessing step for ML algorithms (e.g., KNN, SVM) that are sensitive to feature scales.


In [57]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Find the maximum and minimum values of the array
minimum = sepallength.min()
maximum = sepallength.max()

# Normalize the array to the range [0, 1] using the formula: (x - min) / (max - min)
# max - min gives the range for the data
# subtract every value in the array by the min value, then divide by the range to scale the values to [0, 1]
normalised = (sepallength - minimum) / (maximum - minimum)

print(np.round(normalised, 3))

[0.222 0.167 0.111 0.083 0.194 0.306 0.083 0.194 0.028 0.167 0.306 0.139
 0.139 0.    0.417 0.389 0.306 0.222 0.389 0.222 0.306 0.222 0.083 0.222
 0.139 0.194 0.194 0.25  0.25  0.111 0.139 0.306 0.25  0.333 0.167 0.194
 0.333 0.167 0.028 0.222 0.194 0.056 0.028 0.194 0.222 0.139 0.222 0.083
 0.278 0.194 0.75  0.583 0.722 0.333 0.611 0.389 0.556 0.167 0.639 0.25
 0.194 0.444 0.472 0.5   0.361 0.667 0.361 0.417 0.528 0.361 0.444 0.5
 0.556 0.5   0.583 0.639 0.694 0.667 0.472 0.389 0.333 0.333 0.417 0.472
 0.306 0.472 0.667 0.556 0.361 0.333 0.333 0.5   0.417 0.194 0.361 0.389
 0.389 0.528 0.222 0.389 0.556 0.417 0.778 0.556 0.611 0.917 0.167 0.833
 0.667 0.806 0.611 0.583 0.694 0.389 0.417 0.583 0.611 0.944 0.944 0.472
 0.722 0.361 0.944 0.556 0.667 0.806 0.528 0.5   0.583 0.806 0.861 1.
 0.583 0.556 0.5   0.944 0.556 0.583 0.472 0.722 0.667 0.722 0.417 0.694
 0.667 0.667 0.556 0.611 0.528 0.444]


## 30. Compute the Softmax Score

Compute the softmax scores for the sepallength array.

Difficulty Level: L3

Desired Output:

[ 0.002  0.002  0.001  0.001  0.002  0.003  0.001  0.002  0.001  0.002
  0.003  0.002  0.002  0.001  0.004  0.004  0.003  0.002  0.004  0.002
  0.003  0.002  0.001  0.002  0.002  0.002  0.002  0.002  0.002  0.001
  0.002  0.003  0.002  0.003  0.002  0.002  0.003  0.002  0.001  0.002
  0.002  0.001  0.001  0.002  0.002  0.002  0.002  0.001  0.003  0.002
  0.015  0.008  0.013  0.003  0.009  0.004  0.007  0.002  0.01   0.002
  0.002  0.005  0.005  0.006  0.004  0.011  0.004  0.004  0.007  0.004
  0.005  0.006  0.007  0.006  0.008  0.01   0.012  0.011  0.005  0.004
  0.003  0.003  0.004  0.005  0.003  0.005  0.011  0.007  0.004  0.003
  0.003  0.006  0.004  0.002  0.004  0.004  0.004  0.007  0.002  0.004
  0.007  0.004  0.016  0.007  0.009  0.027  0.002  0.02   0.011  0.018
  0.009  0.008  0.012  0.004  0.004  0.008  0.009  0.03   0.03   0.005
  0.013  0.004  0.03   0.007  0.011  0.018  0.007  0.006  0.008  0.018
  0.022  0.037  0.008  0.007  0.006  0.03   0.007  0.008  0.005  0.013
  0.011  0.013  0.004  0.012  0.011  0.011  0.007  0.009  0.007  0.005]

Why this matters: Softmax converts raw scores into probabilities and is the final activation function in most classification neural networks.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

def softmax(x):
    """
    Compute softmax values for each sets of scores in x.

    Softmax is a function that takes as input a vector of real numbers and normalizes it into a probability distribution. 
    The output values are in the range (0, 1) and sum to 1. 

    The softmax function is often used in machine learning, particularly in classification problems, to convert raw scores (logits) into probabilities.
    """
    e_x = np.exp(x - np.max(x)) # subtracting np.max(x) for numerical stability
    return e_x / e_x.sum(axis=0) # divide the exponentials by the sum of exponentials to get probabilities

print(softmax(sepallength))

AttributeError: 'numpy.ndarray' object has no attribute 'softmax'