# 101 NumPy Exercises for Data Analysis (Python)

## 1. Import NumPy and Check the Version

Import numpy as np and print the version number.

Difficulty Level: L1

Desired Output:

1.13.3

Why this matters: Verifying the NumPy version ensures compatibility with your code and helps debug version-specific behavior differences.

In [2]:
import numpy as np

print(np.__version__)

2.4.6


## 2. Create a 1D Array

Create a 1D array of numbers from 0 to 9.

Difficulty Level: L1

Desired Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Why this matters: Creating sequential arrays is the starting point for indexing exercises, test data generation, and understanding how NumPy stores data in memory.


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Create a Boolean Array

Create a 3×3 numpy array of all True values.

Difficulty Level: L1

Desired Output:

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
 
Why this matters: Boolean arrays are used as masks for filtering data, and understanding how to create them is essential for conditional selection in data analysis.

In [ ]:
# full() is used to create an array filled with a specified value.
arr1 = np.full((3,3,), True)

# or

# ones() is used to create an array filled with ones, and by specifying dtype=bool, 1 = True.
arr2 = np.ones((3, 3), dtype=bool)

print(arr1)
print(arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## 4. Extract Items That Satisfy a Condition

Extract all odd numbers from arr.

Difficulty Level: L1

Desired Output:

array([1, 3, 5, 7, 9])

Why this matters: Boolean indexing is the primary way to filter rows in data cleaning and subsetting datasets before analysis.

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

mask = arr % 2 != 0

# or

result = arr[arr % 2 == 1]

print(arr[mask])
print(result)

[1 3 5 7 9]
[1 3 5 7 9]


## 5. Replace Items That Satisfy a Condition

Replace all odd numbers in arr with -1.

Difficulty Level: L1

Desired Output:

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Why this matters: Conditional replacement is used to handle outliers, recode categories, and clean invalid entries in datasets.

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

mask = arr % 2 != 0

arr[mask]        # read/select values
arr[mask] = -1   # write/replace selected values

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 6. Replace Items Without Affecting the Original Array

Replace all odd numbers in arr with -1 without modifying the original arr.

Difficulty Level: L2

Desired Output:

out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
arr: [0 1 2 3 4 5 6 7 8 9]

Why this matters: Preserving the original data while creating transformed copies is critical in ML pipelines where you need both raw and processed versions of features.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

new = arr.copy()

mask = new % 2 != 0

new[mask] = -1

print(new)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# np.where(condition, value_if_true, value_if_false)
out = np.where(arr % 2 == 1, -1, arr)
print("out:", out)
print("arr:", arr)

out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
arr: [0 1 2 3 4 5 6 7 8 9]


## 7. Reshape an Array

Convert the 1D array arr to a 2D array with 2 rows.

Difficulty Level: L1

Desired Output:

[[0 1 2 3 4]
 [5 6 7 8 9]]
 
Why this matters: Reshaping is one of the most common operations when preparing data for ML models, which expect inputs in specific shapes (e.g., batches of samples).

In [ ]:
arr = np.arange(10)

arr.reshape(2,5)

# or

arr.reshape(2, -1) # -1 means "unspecified", will figure correct size

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. Stack Two Arrays Vertically

Stack arrays a and b vertically.

Difficulty Level: L2

Desired Output:

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
 
Why this matters: Vertical stacking is used to combine datasets, append new observations to existing data, or merge training and validation sets.

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# axis=0 means concatenate along rows (vertical stack)
# axis=1 means concatenate along columns (horizontal stack)
# same as vstack() and hstack() respectively
result = np.concatenate([a, b], axis=0)
print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 9. Stack Two Arrays Horizontally

Stack arrays a and b horizontally.

Difficulty Level: L2

Desired Output:

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
 
Why this matters: Horizontal stacking is used to add new features (columns) to a dataset, such as appending engineered features alongside existing ones.

In [31]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

result = np.concatenate([a, b], axis=1)

print(result)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## 10. Generate Custom Sequences Without Hardcoding

Using only numpy functions and the input array a, produce an array that first repeats each element 3 times, then tiles the whole array 3 times.

Difficulty Level: L2

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Why this matters: Programmatic sequence generation is essential for creating repeated patterns in simulations, data augmentation, and feature engineering.

In [ ]:
a = np.array([1,2,3])

# repeat() repeats each element of the array a specified number of times.
# tile() repeats the whole array a specified number of times.
result = np.concatenate([np.repeat(a, 3), np.tile(a, 3)])
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## 11. Get Common Items Between Two Arrays

Find the common items between arrays a and b.

Difficulty Level: L2

Desired Output:

[2 4]

Why this matters: Set intersection is used in data cleaning to find shared records, overlapping features, or matching IDs across datasets.

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# intersect1d() finds the common elements between two arrays and returns them in sorted order.
result = np.intersect1d(a, b)
print(result)

[2 4]


## 12. Remove Items Present in Another Array

From array a, remove all items that are present in array b.

Difficulty Level: L2

Desired Output:

[1 2 3 4]

Why this matters: Set difference operations are used to exclude known values, filter out stop words, or remove already-processed records from a pipeline.

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# setdiff1d() finds the elements that are in the first array but not in the second array.
result = np.setdiff1d(a, b)  

print(result)

[1 2 3 4]


## 13. Find Positions Where Two Arrays Match

Get the positions (indices) where elements of a and b are equal.

Difficulty Level: L2

Desired Output:

(array([1, 3, 5, 7]),)

Why this matters: Finding matching positions is used in evaluation metrics (e.g., comparing predicted vs. actual labels) and aligning paired datasets.

In [40]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# where() returns the indices where condition you have input is True.
# can access index array using result[0] and result[1] for row and column indices respectively.
result = np.where(a == b)
print(result)

(array([1, 3, 5, 7]),)


## 14. Extract Numbers Within a Given Range

From array a, extract all items between 5 and 10 (inclusive).

Difficulty Level: L2

Desired Output:

[ 6  9 10]

Why this matters: Range-based filtering is used for outlier removal, selecting data within valid bounds, and binning continuous variables.

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
result = a[(a >= 5) & (a <= 10)] # & is used for element-wise logical AND operation
print(result)

# Method 2:
# index = np.where((a >= 5) & (a <= 10))
# print(a[index])

# Method 3:
# index = np.where(np.logical_and(a>=5, a<=10))
# print(a[index])

[ 6  9 10]


## 16. Swap Two Columns in a 2D Array

Swap columns 1 and 2 in the array arr.

Difficulty Level: L2

Desired Output:

[[1 0 2]
 [4 3 5]
 [7 6 8]]
 
Why this matters: Reordering columns is a common step when aligning feature order across datasets or when a model expects features in a specific sequence.

In [ ]:
arr = np.arange(9).reshape(3,3)

# : is used to select all elements along a particular axis.
# syntax is [rows, columns]
arr = arr[:, [1,0,2]]

print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


## 17. Swap Two Rows in a 2D Array

Swap rows 1 and 2 in the array arr.

Difficulty Level: L2

Desired Output:

[[3 4 5]
 [0 1 2]
 [6 7 8]]
 
Why this matters: Row swapping is used in data shuffling, reordering observations, and implementing custom sorting logic for training data.


In [ ]:
arr = np.arange(9).reshape(3,3)

# change order of rows 
result = arr[[1,0,2], :]
print(result)

[[3 4 5]
 [0 1 2]
 [6 7 8]]
